### ISSUE TITLE
keys.h Problem [Solved]

### ISSUE THREAD

**Issue by mohpor** [VoIPGRID/VialerSIPLib-iOS#5]
For those who did a clean `git clone` after last update (834063bbe17abe5d4625a7a4cdee171aa0709fe4), and still getting errors related to `keys.h` not being present:

Fortunately, good guys at VoIPGRID has updated the example project to Swift (I'm not sure if it has been swift from the beginning or not, but thanks anyway). Therefore you should do 3 things:  

1. Rename the `Keys.swift.example` to `Keys.swift`
2. Update the `Keys.swift` with appropriate values (not necessary for a successful build, but you know)
3. Head over to `VialerSIPLib_Example-Bridging-Header.h` and comment out this line:
```objective-c
#import "Keys.h"
```  
i.e. your `VialerSIPLib_Example-Bridging-Header.h` should look something like this:

```objective-c
//
//  Use this file to import your target's public headers that you would like to expose to Swift.
//

//#import "Keys.h"
#import "DDLogWrapper.h"
#import <VialerSIPLib-iOS/VialerSIPLib.h>
#import <VialerSIPLib-iOS/VSLRingtone.h>
```

and you're good to go.

Happy SIPing
M.

**Comment by bobvoorneveld** [comment]
We've starting working on moving the lib to swift indeed. Starting in the Example app of the library. I've missed the reference to Keys.h in the bridging-header (I kept mine because it still had some usefull testing credentials. With the new release all references to Keys.h are gone, except for in the .gitignore, so that anyone with still an old file, isn't accidentally committing their credentials to their repo.
